### ISSUE TITLE
Stardex doesn't seem to work anymore

### ISSUE THREAD

**Issue by axurous** [tipsypastels/stardex#23]
I love the StarDex tool but it seems like the webpage hasn't been able to load up for the past month.

**Comment by tipsypastels** [comment]
I took down the public instance, domain name renewals (and to a smaller extent, hosting services) are not free and I've not had a need for it in years. You can run Stardex locally as a React app and it will work exactly the same.

```bash
$ git clone https://github.com/tipsypastels/stardex
$ cd stardex
$ yarn install
$ yarn start
```

I plan to bring back a public instance and probably give the app a facelift when I have the time and spending money to do so, but that probably won't be soon.
